root_links:
  - lbr4_base_link
  - lbr4_base_link
  - lbr4_base_link
  - lbr4_base_link
  - lbr4_base_link

tip_links:
  - palm_link
  - index_tip
  - middle_tip
  - ring_tip
  - thumb_tip

p_gains:
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0
  - 10.0

d_gains:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  - 0.01

torque_limits:
  # these are artificially high values for sim, can change to be realistic if you want
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
  - 100.0
