# Publish all joint states for joint in associated robot_description
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100  

# effort Controllers ---------------------------------------
lbr4_j0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: lbr4_j0
  pid: {p: 1.0 , i: 0.0, d: 0.}
lbr4_j1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: lbr4_j1
  pid: {p: 1.0 , i: 0.0, d: 0.}
lbr4_j2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: lbr4_j2
  pid: {p: 1.0 , i: 0.0, d: 0.}
lbr4_j3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: lbr4_j3
  pid: {p: 1.0 , i: 0.0, d: 0.}
lbr4_j4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: lbr4_j4
  pid: {p: 1.0 , i: 0.0, d: 0.}
lbr4_j5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: lbr4_j5
  pid: {p: 1.0 , i: 0.0, d: 0.}
lbr4_j6_effort_controller:
  type: effort_controllers/JointEffortController
  joint: lbr4_j6
  pid: {p: 1.0 , i: 0.0, d: 0.}

