# Effort Controllers needs to be tuned ---------------------------------------
index_joint_0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: index_joint_0
  pid: {p: 1.0, i: 0.0, d: 0.0}
index_joint_1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: index_joint_1
  pid: {p: 1.0, i: 0.0, d: 0}
index_joint_2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: index_joint_2
  pid: {p: 1.0, i: 0.0, d: 0}
index_joint_3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: index_joint_3
  pid: {p: 1.0, i: 0.0, d: 0}
middle_joint_0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: middle_joint_0
  pid: {p: 1.0, i: 0.0, d: 0}
middle_joint_1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: middle_joint_1
  pid: {p: 1.0, i: 0.0, d: 0}
middle_joint_2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: middle_joint_2
  pid: {p: 1.0, i: 0.0, d: 0}
middle_joint_3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: middle_joint_3
  pid: {p: 1.0, i: 0.0, d: 0}
ring_joint_0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: ring_joint_0
  pid: {p: 1.0, i: 0.0, d: 0}
ring_joint_1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: ring_joint_1
  pid: {p: 1.0, i: 0.0, d: 0}
ring_joint_2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: ring_joint_2
  pid: {p: 1.0, i: 0.0, d: 0}
ring_joint_3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: ring_joint_3
  pid: {p: 1.0, i: 0.0, d: 0}
thumb_joint_0_effort_controller:
  type: effort_controllers/JointEffortController
  joint: thumb_joint_0
  pid: {p: 1.0, i: 0.0, d: 0}
thumb_joint_1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: thumb_joint_1
  pid: {p: 1.0, i: 0.0, d: 0}
thumb_joint_2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: thumb_joint_2
  pid: {p: 1.0, i: 0.0, d: 0}
thumb_joint_3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: thumb_joint_3
  pid: {p: 1.0, i: 0.0, d: 0}
  