<?xml version="1.0" ?>
<robot name="gripper" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find ll4ma_robots_description)/robots/baxter/finger.xacro" />
  
  <xacro:macro name="gripper" params="side finger_type tip_type finger_slot finger_grasp">
    <xacro:property name="gripper_side" value="${side[0]}" />
    <xacro:property name="l_finger_offset" value="${((finger_slot-1)*0.0095) -0.011}" />
    <xacro:property name="r_finger_offset" value="${((finger_slot-1)*-0.0095) +0.011}" />
    
    <!-- gripper base -->
    <link name="${side}_gripper_base">
      <visual>
        <origin rpy="${-pi/2} ${pi} 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://ll4ma_robots_description/meshes/baxter/grippers/gripper_base.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin rpy="${-pi/2} ${pi} 0" xyz="0.0 0.0 0"/>
        <geometry>
          <cylinder length="0.1" radius="0.029"/>
        </geometry>
        <material name="darkred">
          <color rgba=".5 .1 .1 1"/>
        </material>
      </collision>
      <inertial>
        <origin rpy="${-pi/2} ${pi} 0" xyz="0.0 0.0 0.0"/>
        <mass value="0.3"/>
        <inertia ixx="2e-08" ixy="0" ixz="0" iyy="3e-08" iyz="0" izz="2e-08"/>
      </inertial>
    </link>
      
    <!-- left finger link -->
    <xacro:finger
    	gripper_side="${gripper_side}"
    	finger_side="l"
    	finger_type="${finger_type}"
    	tip_type="${tip_type}"
    	reflect="1"
    	finger_grasp="${finger_grasp}"/>
    
    <!-- <xacro:property name="tip_finger_length" value="${finger_length}" /> -->
    
    <!-- <!-\- right finger link -\-> -->
    <!-- <xacro:finger_xacro -->
    <!-- 	gripper_side="${gripper_side}" -->
    <!-- 	finger_side="r" -->
    <!-- 	finger_type="${finger_type}" -->
    <!-- 	tip_type="${tip_type}" -->
    <!-- 	reflect="-1" -->
    <!-- 	finger_grasp="${finger_grasp}"/> -->
    
    <!-- <xacro:if value="${finger_length > tip_finger_length}"> -->
    <!--   <xacro:property name="tip_finger_length" value="${finger_length}" /> -->
    <!-- </xacro:if> -->
          
    <!-- <!-\- gripper tip link -\-> -->
    <!-- <link name="${side}_gripper"> -->
    <!--   <inertial> -->
    <!--     <origin rpy="0 0 0" xyz="0 0 0"/> -->
    <!--     <mass value="0.0001"/> -->
    <!--     <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0.0"/> -->
    <!--   </inertial> -->
    <!-- </link> -->

    <!-- <!-\- gripper base joint -\-> -->
    <!-- <joint name="${side}_gripper_base" type="fixed"> -->
    <!--   <origin rpy="0 0 0" xyz="0 0 0.025"/> -->
    <!--   <parent link="${side}_hand"/> -->
    <!--   <child link="${side}_gripper_base"/> -->
    <!-- </joint> -->

    <!-- <!-\- gripper tip joint -\-> -->
    <!-- <joint name="${side}_endpoint" type="fixed"> -->
    <!--   <origin rpy="0 0 0" xyz="0 0 ${tip_finger_length+0.02}"/> -->
    <!--   <parent link="${side}_gripper_base"/> -->
    <!--   <child link="${side}_gripper"/> -->
    <!-- </joint> -->
    
    <!-- <!-\- left finger joint -\-> -->
    <!-- <joint name="${gripper_side}_gripper_l_finger_joint" type="prismatic"> -->
    <!--   <origin rpy="0 0 0" xyz="0.0 ${l_finger_offset} 0.02"/> -->
    <!--   <axis xyz="0 1 0"/> -->
    <!--   <parent link="${side}_gripper_base"/> -->
    <!--   <child link="${gripper_side}_gripper_l_finger"/> -->
    <!--   <limit effort="20.0" lower="0.0" upper="0.020833" velocity="5.0"/> -->
    <!--   <dynamics damping="0.7" friction="0.0"/> -->
    <!-- </joint> -->
    
    <!-- <!-\- right finger joint -\-> -->
    <!-- <joint name="${gripper_side}_gripper_r_finger_joint" type="prismatic"> -->
    <!--   <origin rpy="0 0 0" xyz="0.0 ${r_finger_offset} 0.02"/> -->
    <!--   <axis xyz="0 1 0"/> -->
    <!--   <parent link="${side}_gripper_base"/> -->
    <!--   <child link="${gripper_side}_gripper_r_finger"/> -->
    <!--   <limit effort="20.0" lower="-0.020833" upper="0.0" velocity="5.0"/> -->
    <!--   <mimic joint="${gripper_side}_gripper_l_finger_joint" multiplier="-1.0"/> -->
    <!--   <dynamics damping="0.7" friction="0.0"/> -->
    <!-- </joint> -->

    <!-- <!-\- transmissions -\-> -->
    <!-- <transmission name="gripper_${side}1"> -->
    <!--   <type>transmission_interface/SimpleTransmission</type> -->
    <!--   <joint name="${gripper_side}_gripper_r_finger_joint"> -->
    <!--     <hardwareInterface>EffortJointInterface</hardwareInterface> -->
    <!--   </joint> -->
    <!--   <actuator name="gripper_${gripper_side}1_motor1"> -->
    <!--     <hardwareInterface>EffortJointInterface</hardwareInterface> -->
    <!--     <mechanicalReduction>1</mechanicalReduction> -->
    <!--   </actuator> -->
    <!-- </transmission> -->
    <!-- <transmission name="gripper_${side}2"> -->
    <!--   <type>transmission_interface/SimpleTransmission</type> -->
    <!--   <joint name="${gripper_side}_gripper_l_finger_joint"> -->
    <!--     <hardwareInterface>EffortJointInterface</hardwareInterface> -->
    <!--   </joint> -->
    <!--   <actuator name="gripper_${gripper_side}1_motor2"> -->
    <!--     <hardwareInterface>EffortJointInterface</hardwareInterface> -->
    <!--     <mechanicalReduction>1</mechanicalReduction> -->
    <!--   </actuator> -->
    <!-- </transmission> -->

    <!-- <!-\- Gazebo-specific properties -\-> -->
    <!-- <gazebo reference="${gripper_side}_gripper_r_finger_joint"> -->
    <!--   <implicitSpringDamper>1</implicitSpringDamper> -->
    <!-- </gazebo> -->
    <!-- <gazebo reference="${gripper_side}_gripper_l_finger_joint"> -->
    <!--   <implicitSpringDamper>1</implicitSpringDamper> -->
    <!-- </gazebo> -->
    
  </xacro:macro>
 
</robot>
